### ISSUE TITLE
Error when opening chat

### ISSUE THREAD

**Issue by TunableRoom9** [bad-day/TelegramTUI#12]
So really liking the client so far. A bit slow, but I'm guessing that will be addressed in the future. I have no problem sending messages, etc. However, there's one chat I cannot access. Every time I open it I get the following error:
```
/usr/local/lib/python3.6/dist-packages/telethon/telegram_client.py:1092: UserWarning: get_message_history is deprecated, use get_messages instead
  'get_message_history is deprecated, use get_messages instead'
Traceback (most recent call last):
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/eveventhandler.py", line 47, in handle_event
    handler(event)
  File "/home/smvg/Downloads/TelegramTUI/src/MainForm.py", line 73, in event_chat_select
    self.messageBoxObj.update_messages(current_user)
  File "/home/smvg/Downloads/TelegramTUI/src/messageBox.py", line 25, in update_messages
    messages = self.get_messages_info(current_user)
  File "/home/smvg/Downloads/TelegramTUI/src/messageBox.py", line 116, in get_messages_info
    self.prepare_media(out, media, name, image_name, read, mess_id, color, date)
  File "/home/smvg/Downloads/TelegramTUI/src/messageBox.py", line 253, in prepare_media
    if not os.path.isfile(os.getcwd() + "/downloads/" + str(media.photo.id) + ".jpg"):
AttributeError: 'NoneType' object has no attribute 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./telegramTUI", line 5, in <module>
    TelegeramTUI.run()
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/fm_form_edit_loop.py", line 47, in edit
    self.edit_loop()
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/fm_form_edit_loop.py", line 38, in edit_loop
    self._widgets__[self.editw].edit()
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/wgboxwidget.py", line 164, in edit
    self.entry_widget.edit()
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/wgmultiline.py", line 596, in edit
    self.get_and_use_key_press()
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/wgwidget.py", line 575, in get_and_use_key_press
    return self.try_while_waiting()
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/wgwidget.py", line 560, in try_while_waiting
    self.parent.parentApp._internal_while_waiting()
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/apNPSApplicationEvents.py", line 41, in _internal_while_waiting
    self.process_event_queues(max_events_per_queue=self.max_events_per_queue)
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/apNPSApplicationEvents.py", line 52, in process_event_queues
    self.process_event(event)
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/apNPSApplicationEvents.py", line 70, in process_event
    result = registered_object.handle_event(event)
  File "/home/smvg/Downloads/TelegramTUI/src/npyscreen/eveventhandler.py", line 48, in handle_event
    except weakref.ReferenceError:
AttributeError: module 'weakref' has no attribute 'ReferenceError'

```

Keep up the good work!

**Comment by bad-day** [comment]
Fixed

**Comment by TunableRoom9** [comment]
Wow that was quick! It works now :)
