### ISSUE TITLE
I can't start it

### ISSUE THREAD

**Issue by pokemonchw** [bad-day/TelegramTUI#15]
`/usr/lib/python3.6/site-packages/telethon/telegram_client.py:1212: UserWarning: get_message_history is deprecated, use get_messages instead
  'get_message_history is deprecated, use get_messages instead'
Traceback (most recent call last):
  File "./telegramTUI", line 2, in <module>
    from src.ui import App
  File "/home/byayoi/workspace/TelegramTUI/src/ui.py", line 2, in <module>
    from src.MainForm import MainForm
  File "/home/byayoi/workspace/TelegramTUI/src/MainForm.py", line 4, in <module>
    from src.telegramApi import client
  File "/home/byayoi/workspace/TelegramTUI/src/telegramApi.py", line 196, in <module>
    client = TelegramApi()
  File "/home/byayoi/workspace/TelegramTUI/src/telegramApi.py", line 76, in __init__
    @self.client.on(events.Raw(chats=None, blacklist_chats=False))
TypeError: __init__() got an unexpected keyword argument 'chats'`

**Comment by bad-day** [comment]
Fixed
