### ISSUE TITLE
Isn't better to show an error message when socket.timeout except crashing?

### ISSUE THREAD

**Issue by TheYahya** [bad-day/TelegramTUI#17]
```
Traceback (most recent call last):
  File "./telegramTUI", line 2, in <module>
    from src.ui import App
  File "/home/yahya/dev/python/TelegramTUI/src/ui.py", line 2, in <module>
    from src.MainForm import MainForm
  File "/home/yahya/dev/python/TelegramTUI/src/MainForm.py", line 4, in <module>
    from src.telegramApi import client
  File "/home/yahya/dev/python/TelegramTUI/src/telegramApi.py", line 196, in <module>
    client = TelegramApi()
  File "/home/yahya/dev/python/TelegramTUI/src/telegramApi.py", line 47, in __init__
    self.client.start()
  File "/usr/local/lib/python3.6/dist-packages/telethon/telegram_client.py", line 313, in start
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/telethon/telegram_bare_client.py", line 207, in connect
    self._sender.connect()
  File "/usr/local/lib/python3.6/dist-packages/telethon/network/mtproto_sender.py", line 68, in connect
    self.connection.connect(self.session.server_address, self.session.port)
  File "/usr/local/lib/python3.6/dist-packages/telethon/network/connection/tcpfull.py", line 25, in connect
    self.conn.connect(ip, port)
  File "/usr/local/lib/python3.6/dist-packages/telethon/extensions/tcp_client.py", line 78, in connect
    self._socket.connect(address)
  File "/usr/local/lib/python3.6/dist-packages/socks.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/socks.py", line 825, in connect
    super(socksocket, self).connect((dest_addr, dest_port))
socket.timeout: timed out
```

**Comment by bad-day** [comment]
Thanks for reporting!
I've made changes to the repository
