### ISSUE TITLE
Can’t start TelegramTUI

### ISSUE THREAD

**Issue by AkitakiKou** [bad-day/TelegramTUI#20]
Upon start it fails with the error message below. 
OS: Ubuntu 16.04

```
/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py:1368: UserWarning: get_message_history is deprecated, use get_messages instead
  'get_message_history is deprecated, use get_messages instead'
Traceback (most recent call last):
  File "./telegramTUI", line 5, in <module>
    TelegeramTUI.run()
  File "/home/akitaki/Downloads/TelegramTUI/src/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/home/akitaki/Downloads/TelegramTUI/src/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/home/akitaki/Downloads/TelegramTUI/src/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/home/akitaki/Downloads/TelegramTUI/src/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/home/akitaki/Downloads/TelegramTUI/src/npyscreen/apNPSApplicationManaged.py", line 148, in main
    self.onStart()
  File "/home/akitaki/Downloads/TelegramTUI/src/ui.py", line 13, in onStart
    self.MainForm = self.addForm("MAIN", MainForm)
  File "/home/akitaki/Downloads/TelegramTUI/src/npyscreen/apNPSApplicationManaged.py", line 55, in addForm
    fm = FormClass( parentApp=self, *args, **keywords)
  File "/home/akitaki/Downloads/TelegramTUI/src/npyscreen/fmForm.py", line 70, in __init__
    self.create()
  File "/home/akitaki/Downloads/TelegramTUI/src/MainForm.py", line 71, in create
    self.chatBoxObj.update_chat()
  File "/home/akitaki/Downloads/TelegramTUI/src/chatBox.py", line 42, in update_chat
    mute_until = int(client.dialogs[i].dialog.notify_settings.mute_until)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by bad-day** [comment]
Thank you for reporting, this bug has already been fixed.
Update telethon with `sudo pip3 install telethon==0.19.1.6`

**Comment by AkitakiKou** [comment]
Confirmed that it’s working now. Thanks for the quick reply!
