### ISSUE TITLE
Crashes on startup, telegramApi.py line 46

### ISSUE THREAD

**Issue by CraigBlaylock** [bad-day/TelegramTUI#23]
root@Bubo:~/TelegramTUI# ./telegramTUI                                                   
Traceback (most recent call last):                                                       
  File "./telegramTUI", line 2, in <module>                                              
    from src.ui import App                                                               
  File "/root/TelegramTUI/src/ui.py", line 2, in <module>                                
    from src.MainForm import MainForm                                                    
  File "/root/TelegramTUI/src/MainForm.py", line 4, in <module>                          
    from src.telegramApi import client                                                   
  File "/root/TelegramTUI/src/telegramApi.py", line 200, in <module>                     
    client = TelegramApi()                                                               
  File "/root/TelegramTUI/src/telegramApi.py", line 46, in __init__                      
    spawn_read_thread=True, proxy=proxy)                                                 
TypeError: __init__() got an unexpected keyword argument 'spawn_read_thread'             
root@Bubo:~/TelegramTUI# sudo ./telegramTUI                                              
Traceback (most recent call last):                                                       
  File "./telegramTUI", line 2, in <module>                                              
    from src.ui import App                                                               
  File "/root/TelegramTUI/src/ui.py", line 2, in <module>                                
    from src.MainForm import MainForm                                                    
  File "/root/TelegramTUI/src/MainForm.py", line 4, in <module>                          
    from src.telegramApi import client                                                   
  File "/root/TelegramTUI/src/telegramApi.py", line 200, in <module>                     
    client = TelegramApi()                                                               
  File "/root/TelegramTUI/src/telegramApi.py", line 46, in __init__                      
    spawn_read_thread=True, proxy=proxy)                                                 
TypeError: __init__() got an unexpected keyword argument 'update_workers'   

Let me know if there's anything I can provide to assist in troubleshooting.

**Comment by BrokeRU** [comment]
The same trouble for me.
![default](https://user-images.githubusercontent.com/9129071/43034613-12aac0b2-8cf9-11e8-80bd-faa4d8067e55.png)

**Comment by BrokeRU** [comment]
omg TelegramTUI is completely broken with latest Telethon. They are using `async` features now.

**Comment by BrokeRU** [comment]
`pip install telethon==0.19.1.6`
Working solution.

**Comment by CraigBlaylock** [comment]
Well, that's one issue fixed. Looks like there's another:


```
root@Bubo:~/TelegramTUI$ ./telegramTUI                                                                                                                      
Please enter your phone: ##########                                                                                                                                                                                           
Please enter the code you received: #####                                                                                                                                 Please enter your password:                                                                                                                                                                            Signed in successfully as ####                                                                                                                                                                                    /usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py:1368: UserWarning:                                                    
  'get_message_history is deprecated, use get_messages instead'                                                                                                                                                                
Traceback (most recent call last):                                                                                                                                                              
  File "/home/knightly/TelegramTUI/src/npyscreen/eveventhandler.py", line 47, in handle_event                                                                                
    handler(event)                                                                                                                                                          
  File "/home/knightly/TelegramTUI/src/MainForm.py", line 79, in event_chat_select                                                                                                                                             
    self.messageBoxObj.update_messages(current_user)                                                                                                                                                                                 
  File "/home/knightly/TelegramTUI/src/messageBox.py", line 54, in update_messages                                                                                                          
    self.display()                                                                                                                                                                          
  File "/home/knightly/TelegramTUI/src/npyscreen/wgwidget.py", line 429, in display                                                                                                          
    self.update()                                                                                                                                               /usr/bin/glances
  File "/home/knightly/TelegramTUI/src/npyscreen/wgboxwidget.py", line 155, in update                                                                           /usr/bin/glances
    w.update(clear=clear)                                                                                                                                       
  File "/home/knightly/TelegramTUI/src/npyscreen/wgmultiline.py", line 271, in update                                                                           
    if (self._my_widgets[self.cursor_line - self.start_display_at].task in (MORE_LABEL, "PRINTLINELASTOFSCREEN")):                                              
IndexError: list index out of range                                                                                                                            
During handling of the above exception, another exception occurred:                                                                                            
                                                                                                                                                              Traceback (most recent call last):                                                                                                                                         
  File "./telegramTUI", line 5, in <module>                                                                                                                     
    TelegeramTUI.run()                                                                                                                                          
  File "/home/knightly/TelegramTUI/src/npyscreen/apNPSApplication.py", line 30, in run                                                                                                       
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)                                                                                            
  File "/home/knightly/TelegramTUI/src/npyscreen/npyssafewrapper.py", line 41, in wrapper                                                                       
    wrapper_no_fork(call_function)                                                                                                                              
  File "/home/knightly/TelegramTUI/src/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork                                                               
    return_code = call_function(_SCREEN)                                                                                                                        
  File "/home/knightly/TelegramTUI/src/npyscreen/apNPSApplication.py", line 25, in 
    return self.main()                                                                                                                                          
  File "/home/knightly/TelegramTUI/src/npyscreen/apNPSApplicationManaged.py", line 172, in main                                                                
    self._THISFORM.edit()                                                                                                                                      
  File "/home/knightly/TelegramTUI/src/npyscreen/fm_form_edit_loop.py", line 47, in edit                                                                       
    self.edit_loop()                                                               
  File "/home/knightly/TelegramTUI/src/npyscreen/fm_form_edit_loop.py", line 38, in edit_loop                                                                   
    self._widgets__[self.editw].edit()                                                                                                                         
  File "/home/knightly/TelegramTUI/src/npyscreen/wgboxwidget.py", line 164, in edit                                                                             
    self.entry_widget.edit()                                                                                                                                               
  File "/home/knightly/TelegramTUI/src/npyscreen/wgmultiline.py", line 596, in edit                                                                             
    self.get_and_use_key_press()                                                                                                                                
  File "/home/knightly/TelegramTUI/src/npyscreen/wgwidget.py", line 575, in get_and_use_key_press                                                                                            
    return self.try_while_waiting()                                                                                                                             
  File "/home/knightly/TelegramTUI/src/npyscreen/wgwidget.py", line 560, in try_while_waiting                                                                   
    self.parent.parentApp._internal_while_waiting()                                                                                                             
  File "/home/knightly/TelegramTUI/src/npyscreen/apNPSApplicationEvents.py", line 41, in     self.process_event_queues(max_events_per_queue=self.max_events_per_queue)                                                                                   
  File "/home/knightly/TelegramTUI/src/npyscreen/apNPSApplicationEvents.py", line 52, in
    self.process_event(event)                                                                                                                                   
  File "/home/knightly/TelegramTUI/src/npyscreen/apNPSApplicationEvents.py", line 70, in process_event                                                 
    result = registered_object.handle_event(event)                                                                                                             
  File "/home/knightly/TelegramTUI/src/npyscreen/eveventhandler.py", line 48, in handle_event                                                                  
    except weakref.ReferenceError:                                                                                                                             
AttributeError: module 'weakref' has no attribute 'ReferenceError'  
```

**Comment by bad-day** [comment]
Thanks for reporting, I will refactor the code in the near future.
