### ISSUE TITLE
Telegram don’t start

### ISSUE THREAD

**Issue by Antoxa223** [bad-day/TelegramTUI#27]
ubuntu@ip-172-31-36-140:~$ sudo TelegramTUI/./telegramTUITraceback (most recent call last):  File "/usr/lib/python3.4/configparser.py", line 1116, in _unify_values    sectiondict = self._sections[section]KeyError: 'telegram_api'During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "TelegramTUI/./telegramTUI", line 2, in <module>    from src.ui import App  File "/home/ubuntu/TelegramTUI/src/ui.py", line 2, in <module>    from src.MainForm import MainForm  File "/home/ubuntu/TelegramTUI/src/MainForm.py", line 4, in <module>    from src.telegramApi import client  File "/home/ubuntu/TelegramTUI/src/telegramApi.py", line 200, in <module>    client = TelegramApi()  File "/home/ubuntu/TelegramTUI/src/telegramApi.py", line 20, in __init__    api_id = config.get('telegram_api', 'api_id')  File "/usr/lib/python3.4/configparser.py", line 754, in get    d = self._unify_values(section, vars)  File "/usr/lib/python3.4/configparser.py", line 1119, in _unify_values    raise NoSectionError(section)configparser.NoSectionError: No section: 'telegram_api'ubuntu@ip-172-31-36-140:~$

**Comment by bad-day** [comment]
Are you install all dependensies?
Please, send me traceback in utf8.
