### ISSUE TITLE
App crashes upon attempt to send an empty message

### ISSUE THREAD

**Issue by ziforigin** [bad-day/TelegramTUI#6]
Reproduction:
Open any chat-box, dont't type anything, press "send" sequence.

Result:
`/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py:1092: UserWarning: get_message_history is deprecated, use get_messages instead
  'get_message_history is deprecated, use get_messages instead'
Traceback (most recent call last):
  File "./telegramTUI", line 5, in <module>
    TelegeramTUI.run()
  File "/opt/git/TelegramTUI/src/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/opt/git/TelegramTUI/src/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/opt/git/TelegramTUI/src/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/opt/git/TelegramTUI/src/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/opt/git/TelegramTUI/src/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/opt/git/TelegramTUI/src/npyscreen/fm_form_edit_loop.py", line 47, in edit
    self.edit_loop()
  File "/opt/git/TelegramTUI/src/npyscreen/fm_form_edit_loop.py", line 38, in edit_loop
    self._widgets__[self.editw].edit()
  File "/opt/git/TelegramTUI/src/npyscreen/wgboxwidget.py", line 164, in edit
    self.entry_widget.edit()
  File "/opt/git/TelegramTUI/src/npyscreen/wgwidget.py", line 458, in edit
    self._edit_loop()
  File "/opt/git/TelegramTUI/src/npyscreen/wgwidget.py", line 474, in _edit_loop
    self.get_and_use_key_press()
  File "/opt/git/TelegramTUI/src/npyscreen/wgwidget.py", line 610, in get_and_use_key_press
    self.handle_input(ch)
  File "/opt/git/TelegramTUI/src/npyscreen/wgwidget.py", line 92, in handle_input
    if self.parent_widget.handle_input(_input):
  File "/opt/git/TelegramTUI/src/npyscreen/wgwidget.py", line 95, in handle_input
    if self.parent.handle_input(_input):
  File "/opt/git/TelegramTUI/src/npyscreen/wgwidget.py", line 80, in handle_input
    self.handlers[_unctrl_input](_input)
  File "/opt/git/TelegramTUI/src/ui.py", line 88, in message_send
    client.message_send(message, current_user)
  File "/opt/git/TelegramTUI/src/telegramApi.py", line 127, in message_send
    data = self.client.send_message(self.dialogs[user_id].entity, message)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 753, in send_message
    'The message cannot be empty unless a file is provided'
ValueError: The message cannot be empty unless a file is provided`

**Comment by bad-day** [comment]
Fixed

**Comment by ziforigin** [comment]
Not really:
Steps to reproduce:
In chat-box press Enter; the cursor will move 1 line down, so message string will contain only invisible "new line" character; then press "Send" sequence.

Result:
/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py:1092: UserWarning: get_message_history is deprecated, use get_messages instead
  'get_message_history is deprecated, use get_messages instead'
Traceback (most recent call last):
  File "./telegramTUI", line 5, in <module>
    TelegeramTUI.run()
  File "/opt/git/TelegramTUI/src/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/opt/git/TelegramTUI/src/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/opt/git/TelegramTUI/src/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/opt/git/TelegramTUI/src/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/opt/git/TelegramTUI/src/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/opt/git/TelegramTUI/src/npyscreen/fm_form_edit_loop.py", line 47, in edit
    self.edit_loop()
  File "/opt/git/TelegramTUI/src/npyscreen/fm_form_edit_loop.py", line 38, in edit_loop
    self._widgets__[self.editw].edit()
  File "/opt/git/TelegramTUI/src/npyscreen/wgboxwidget.py", line 164, in edit
    self.entry_widget.edit()
  File "/opt/git/TelegramTUI/src/npyscreen/wgwidget.py", line 458, in edit
    self._edit_loop()
  File "/opt/git/TelegramTUI/src/npyscreen/wgwidget.py", line 474, in _edit_loop
    self.get_and_use_key_press()
  File "/opt/git/TelegramTUI/src/npyscreen/wgwidget.py", line 610, in get_and_use_key_press
    self.handle_input(ch)
  File "/opt/git/TelegramTUI/src/npyscreen/wgwidget.py", line 92, in handle_input
    if self.parent_widget.handle_input(_input):
  File "/opt/git/TelegramTUI/src/npyscreen/wgwidget.py", line 95, in handle_input
    if self.parent.handle_input(_input):
  File "/opt/git/TelegramTUI/src/npyscreen/wgwidget.py", line 80, in handle_input
    self.handlers[_unctrl_input](_input)
  File "/opt/git/TelegramTUI/src/ui.py", line 87, in message_send
    client.message_send(message, current_user)
  File "/opt/git/TelegramTUI/src/telegramApi.py", line 127, in message_send
    data = self.client.send_message(self.dialogs[user_id].entity, message)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 788, in send_message
    result = self(request)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 450, in __call__
    result = self._invoke(call_receive, *requests)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 542, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.MessageEmptyError: Empty or invalid UTF-8 message was sent

**Comment by bad-day** [comment]
Please, check again

**Comment by ziforigin** [comment]
Resolved
